theme = "onedark"

[editor]
line-number = "relative"
mouse = false

[editor.cursor-shape]
normal = "block"
#insert = "bar"

[keys.normal]
j = "move_char_left"
";" = "move_char_right"
k = "move_line_down"
l = "move_line_up"
"esc" = "command_mode"
a = ["append_mode", "collapse_selection"]
h = "collapse_selection"

[keys.normal.g]
";" = "goto_line_end"
j = "goto_line_start"
k = ["move_line_down", "move_line_down", "move_line_down", "move_line_down", "move_line_down"]
l = ["move_line_up", "move_line_up", "move_line_up", "move_line_up", "move_line_up"]


[keys.insert.j]
k = "move_char_right"

[keys.select]
h = "collapse_selection"
j = "extend_char_left"
";" = "extend_char_right"
k = "extend_visual_line_down"
l = "extend_visual_line_up"
"esc" = "normal_mode"
